version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=lovesync
      - POSTGRES_PASSWORD=loveSync2025
      - POSTGRES_DB=love_sync
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
